import { store } from '@/redux/store'
import './globals.css'
import  { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider,useDispatch, useSelector } from 'react-redux'
import React, { useEffect, useState } from 'react'
import axios from "axios";
import Statecom from '@/components/Statecom'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}) {

  // const dispatch = useDispatch();
  // const count = useSelector((state) => {console.log("rrrmain",state.authuser); return state.counter.value})


  // const dispatch = useDispatch();

  // useEffect(()=>{

  //   const getUserDetails = async () => {
  //     try {
  //       const res = await axios.get('/api/users/me')
  //       console.log("res main",res.data.user);
  //       // dispatch(setAuthuser({isloggedin:true,user:res.data.user}));

  //     } catch (error) {
  //       console.log("res mainerrr");
  //       // dispatch(setAuthuser({isloggedin:true,user:null}));


  //     }
     
  // }
  // //  getUserDetails();
  // },[]);



  return (
    
    <html lang="en">
      <Provider store={store}>
         <body className={inter.className}>{children}<Statecom/></body>
      </Provider>


    </html>
  )
}
